In [2]:
import torch
from torch import nn
import matplotlib.pyplot as plt
import numpy as np

print(torch.cuda.is_available())

True


In [3]:
# create known paramters
# creating data
weight = 0.7
bias = 0.3

# data
start = 0
end = 1
step = 0.02
# x is capital because it's a matrix or tensor
X = torch.arange(start, end, step).unsqueeze(dim=1)  # adds an extra dimension
y = weight * X + bias
X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [4]:
class CircleModelV1(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer_1 = nn.Linear(in_features=2, out_features=10)
        self.layer_2 = nn.Linear(in_features=10, out_features=10)
        self.layer_3 = nn.Linear(in_features=10, out_features=1)

    def forward(self, x):
        return self.layer_3(self.layer_2(self.layer_1(x)))

In [5]:
model_1 = CircleModelV1().to(device="cuda")
model_1.state_dict()

OrderedDict([('layer_1.weight',
              tensor([[ 0.6251,  0.5148],
                      [ 0.0571, -0.0417],
                      [ 0.3001, -0.6903],
                      [-0.6791, -0.2785],
                      [-0.6127, -0.2117],
                      [ 0.3792, -0.0027],
                      [ 0.1240, -0.3481],
                      [ 0.4976,  0.2227],
                      [-0.5739,  0.3807],
                      [ 0.4392,  0.6108]], device='cuda:0')),
             ('layer_1.bias',
              tensor([-0.4351, -0.4806, -0.0941, -0.1108, -0.0419, -0.5202, -0.1508, -0.5010,
                       0.4159, -0.5888], device='cuda:0')),
             ('layer_2.weight',
              tensor([[ 0.2323, -0.1141, -0.1143, -0.2034, -0.0120, -0.0766,  0.2782, -0.0568,
                       -0.2349, -0.1531],
                      [-0.1737,  0.0103, -0.1591, -0.0731,  0.2496,  0.2399,  0.1859,  0.1731,
                       -0.0478, -0.0914],
                      [-0.1681, -0.117